### ISSUE TITLE
hiltViewModelScoped returns new viewModel with old bundle argument on key change

### ISSUE THREAD

**Issue by LightningGem** [sebaslogen/resaca#22]
i have following VM:
```
val viewModel: TorrentDetailsViewModel = hiltViewModelScoped(
        key = hash, defaultArguments = bundleOf(TorrentDetailsViewModel.HASH_KEY to hash)
    )
```
After composable is recomposed with new hash, new viewModel is returned, but bundle hash value is old.
![pic1](https://github.com/sebaslogen/resaca/assets/111201146/f076a99b-db86-4a49-9376-0acc3d21e026)
![pic2](https://github.com/sebaslogen/resaca/assets/111201146/8aa2c4f8-93a6-4a2c-9f53-d1ab03b4d639)

**Comment by sebaslogen** [comment]
Hi there, thanks for reporting it and adding enough details.
I'll work on a fix next week

**Comment by sebaslogen** [comment]
Bug fixed in release https://github.com/sebaslogen/resaca/releases/tag/2.4.5

For reference: 
The bug was the key used in the ViewModelProvider, it was missing the key provided in `hiltViewModelScoped`.
Since the ViewModel was correctly being removed and recreated by the library, the side effect was that the old Bundle from SavedStateHandle was restored.
The fix was to use the provided key in the ViewModelProvider and add an automated test to cover this case.


Thanks again for reporting the issue 😃

**Comment by almozavr** [comment]
We could still see the bug when VM is created inside Dialog composable and this dialog is dismissed and then shown again. Could it be a regression? Lib version is `4.6.4`

**Comment by almozavr** [comment]
I've debugged a bit more and have found the root cause: `NavBackStackEntry` (which in fact is the `ViewModelStoreOwner`) holds cached `savedStateHandlesVM` and provides them on every VM re-creation. 

As seen in `SavedStateHandleSupport` from `lifecycle-viewmodel-savedstate-android`

<img width="973" height="351" alt="Image" src="https://github.com/user-attachments/assets/17f3e64e-7d92-4cc7-a906-f84f2d6e09de" />

<img width="519" height="30" alt="Image" src="https://github.com/user-attachments/assets/284309fc-4b7f-4412-829a-0261d8324ce5" />

Could we make sure the `NavBackStackEntry` as `ViewModelStoreOwner` got involved into resource clean up when `clear` is called? 

P.S. @sebaslogen do we need to create a separate issue?

**Comment by almozavr** [comment]
I could prepare a sample for you in ~12 hrs
